# ----------------------- #
#      Main Configs       #
# ----------------------- #

url: http://yoursite.com
title: Chip-In
description: > # "Write an awesome description for your new site here.
  Split a bill without the nightmare.

# ----------------------- #
#    Jekyll & Plugins     #
# ----------------------- #

# Build settings
markdown: kramdown
permalink: pretty

# ----------------------- #
#   3rd Party Settings    #
# ----------------------- #

social:
  - title: github
    url: https://github.com/iOSCowboy/SoundOfCash-Nordea
